# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|

  config.vm.box_check_update = true
    
  config.vm.provider "libvirt" do |kvm|
    kvm.random :model => 'random'
    kvm.cpu_mode = 'host-passthrough'
    kvm.driver = 'kvm'
    kvm.memory  = 4096
    kvm.cpus    = 2
  end   
  
  config.vm.define "kmaster" do |kmaster|
    kmaster.vm.box = "centos/7"
    kmaster.vm.hostname = "kmaster.example.com"
   
    kmaster.vm.network "private_network", ip: "172.42.42.100",
      libvirt_netmask: '255.255.255.0',
      libvirt__network_name: 'vagrant-kubernetes',
      autostart: true,
      libvirt__forward_mode: 'route',
      libvirt__dhcp_enabled: false
    
    kmaster.vm.provision "shell", :inline => <<-SHELL
      sudo echo -e 'nameserver 8.8.8.8\nnameserver 8.8.4.4\n' > /etc/resolv.conf
      sudo echo "172.42.42.100 kmaster.example.com" | sudo tee -a /etc/hosts
      sudo echo "172.42.42.101 kworker1.example.com" | sudo tee -a /etc/hosts
      sudo echo "172.42.42.102 kworker2.example.com" | sudo tee -a /etc/hosts
    SHELL
    
    kmaster.vm.provider "libvirt" do |v|
      v.random :model => 'random'
      v.cpu_mode = 'host-passthrough'
      v.driver = 'kvm'
      v.memory  = 4096
      v.cpus    = 2
    end
  end

  NodeCount = 2

  (1..NodeCount).each do |i|
    config.vm.define "kworker#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "kworker#{i}.example.com"

      workernode.vm.network "private_network", ip: "172.42.42.10#{i}",
        libvirt_netmask: '255.255.255.0',
        libvirt__network_name: 'vagrant-kubernetes',
        autostart: true,
        libvirt__forward_mode: 'route',
        libvirt__dhcp_enabled: false
      
      workernode.vm.provision "shell", :inline => <<-SHELL
        sudo echo -e 'nameserver 8.8.8.8\nnameserver 8.8.4.4\n' > /etc/resolv.conf
        sudo echo "172.42.42.100 kmaster.example.com" | sudo tee -a /etc/hosts
        sudo echo "172.42.42.101 kworker1.example.com" | sudo tee -a /etc/hosts
        sudo echo "172.42.42.102 kworker2.example.com" | sudo tee -a /etc/hosts
      SHELL

      workernode.vm.provider "libvirt" do |v|
        v.random :model => 'random'
        v.cpu_mode = 'host-passthrough'
        v.driver = 'kvm'
        v.memory  = 4096
        v.cpus    = 2
      end
    
    end
  end
end